# Generated by Django 3.0.6 on 2020-05-20 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('areas', '0001_initial'),
        ('reports', '0002_auto_20200520_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='report',
            name='production_line',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='areas.ProductionLine'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
