# Generated by Django 3.0.6 on 2020-05-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_problemreported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreported',
            options={'verbose_name': 'Problem Reported', 'verbose_name_plural': 'Problems Reported'},
        ),
    ]
